FLAG = -Wall -Werror -Wextra -pedantic
FindDivisors: FindDivisors.o
	gcc -o FindDivisors FindDivisors.o $(FLAG) 
FindDivisors.o: FindDivisors.c FindDivisors.h 
	gcc -c FindDivisors.c $(FLAG) 
FindStrings: FindStrings.o
	gcc -o FindStrings FindStrings.o $(FLAG) 
FindStrings.o: FindStrings.c FindStrings.h 
	gcc -c FindStrings.c $(FLAG) 
CopySubstr: CopySubstr.o
	gcc -o CopySubstr CopySubstr.o $(FLAG) 
CopySubstr.o: CopySubstr.c CopySubstr.h 
	gcc -c CopySubstr.c $(FLAG) 
BST: BST.o
	gcc -o BST BST.o $(FLAG) 
BST.o: BST.c BST.h 
	gcc -c BST.c $(FLAG)
