FLAG = -Wall -Werror -Wextra -pedantic
Conditional: Conditional.o
	gcc -o Conditional Conditional.o $(FLAG) 
Conditional.o: Conditional.c Conditional.h 
	gcc -c Conditional.c $(FLAG) 
Negation: Negation.o
	gcc -o Negation Negation.o $(FLAG) 
Negation.o: Negation.c Negation.h 
	gcc -c Negation.c $(FLAG) 	
AddFloat: AddFloat.o
	gcc -o AddFloat AddFloat.o $(FLAG) 
AddFloat.o: AddFloat.c AddFloat.h 
	gcc -c AddFloat.c $(FLAG) 	
FloatMulti: FloatMulti.o
	gcc -o FloatMulti FloatMulti.o $(FLAG) 
FloatMulti.o: FloatMulti.c FloatMulti.h 
	gcc -c FloatMulti.c $(FLAG) 	
